port: "8000"

db:
  host:     "localhost"
  port:     "5432"
  username: "docker"
  dbname:   "test_db"
  sslmode:  "disable"

redis:
  address: "localhost:6379"
  addr: "localhost"
  port: "6379"
  password: "dockerRedis"